### ISSUE TITLE
Version 1.12 incompatible with zc.buildout 1.7.1

### ISSUE THREAD

**Issue by rafaelbco** [collective/collective.recipe.template#11]
If I try to use the version 1.12 of the recipe to generate a simple file (no genshi involved) with zc.buildout 1.7.1 (latest in the 1.x series) then I get the following traceback:

```
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/rafaelbc/trt3/trt3plone/python_buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1866, in main
    getattr(buildout, command)(args)
  File "/home/rafaelbc/trt3/trt3plone/python_buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 509, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/rafaelbc/trt3/trt3plone/python_buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1104, in __getitem__
    options._initialize()
  File "/home/rafaelbc/trt3/trt3plone/python_buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1192, in _initialize
    self.recipe = recipe_class(buildout, name, self)
  File "/home/rafaelbc/trt3/trt3plone/python_buildout/eggs/collective.recipe.template-1.12-py2.7.egg/collective/recipe/template/__init__.py", line 35, in __init__
    self.overwrite = zc.buildout.buildout.bool_option(options, 'overwrite', True)
AttributeError: 'module' object has no attribute 'bool_option'
```

I think the solution is to restore compatibility with zc.buildout 1.x or increase the version number to 2.x and mention in the documentation this compatibility issue.

Note that zc.buildout 1.7.1 is what you get when you use Plone 4.3.6

**Comment by keul** [comment]
:+1: 

Same issue I encountered yesterday on a legacy buildout (discussed on IRC with @jensens). But I think is an issue on old buildouts as well: they not always respects the version.cfg pinning for recipes.

**Comment by lukasgraf** [comment]
:+1: - I'm also seeing this one crop up all over the place.

I'm thinking about simply reverting @c389c778 - they way it worked before is how to ensure buildout 1.x compatibility. Any objections? @mstaniszczak?

**Comment by hvelarde** [comment]
same over here

**Comment by mstaniszczak** [comment]
@lukasgraf  can you check it from my fork - https://github.com/mstaniszczak/collective.recipe.template? If it's now work for you, I'll send here pull request.

**Comment by lukasgraf** [comment]
@mstaniszczak testing right now

**Comment by lukasgraf** [comment]
@mstaniszczak thanks, works for me :+1:. Can you please add a changelog entry when you do the pull-request?

**Comment by mstaniszczak** [comment]
OK. Pull request created and waiting. Sorry for the inconvenience.

**Comment by lukasgraf** [comment]
Closed via #12.

**Comment by hvelarde** [comment]
a new release will be appreciated :-)

**Comment by aclark4life** [comment]
I'll do one tomorrow morning if no one does it sooner.

**Comment by hvelarde** [comment]
I can do it if I get permission

**Comment by aclark4life** [comment]
hvelarde on PyPI?

**Comment by hvelarde** [comment]
yes, and please add "collective" also

**Comment by aclark4life** [comment]
Done! Release-away :smile:
