### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by icemac** [collective/collective.recipe.template#17]
In 1b29d69 @regebro added Python 3 compatibility, please cut a new release.

**Comment by icemac** [comment]
@aclark4life @fschulze @hvelarde @mitchellrj @tlotze @witsch You have the rights on PyPI to do so.
If you want to share the rights I am ``icemac`` at PyPI.

**Comment by aclark4life** [comment]
Done and thanks
<img width="458" alt="screenshot 2017-01-13 09 25 59" src="https://cloud.githubusercontent.com/assets/72164/21933172/54cdccc8-d972-11e6-8b78-877b99a3d9c3.png">

**Comment by icemac** [comment]
@aclark4life Thank you. I released 2.0: https://pypi.org/project/collective.recipe.template/2.0/
