### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mstaniszczak** [collective/collective.recipe.template#7]
What do you think, about creating new release  (to pypi)? :)

**Comment by mstaniszczak** [comment]
ping;-)

**Comment by davidjb** [comment]
Okay, sorry everyone, but I'm going to ping everyone who's a package manager directly:
@fschulze 
@wichert 
@aclark4life
@mitchellrj 
I'm happy to help make a release, if someone grants me access.

**Comment by fschulze** [comment]
Sorry this took so long.
